name: VPM Listing JSON Builder
description: Builds a JSON file for VPM listing.
author: yukineko-works

branding:
  icon: archive
  color: green

inputs:
  name:
    description: name of vpm repository
    default: example vpm repository
    required: false
  id:
    description: id of vpm repository
    default: com.example.vpm-repository
    required: false
  url:
    description: url of vpm repository's json file
    default: https://example.com/index.json
    required: false
  author:
    description: author name of vpm repository
    default: unknown
    required: false
  repositories:
    description: repositories (packages) to include in the listing
    default: ''
    required: false
  source:
    description: path to the source.json file
    default: ''
    required: false
  output:
    description: output file name
    default: index.json
    required: false
  token:
    description: github token
    required: true
  cache-key:
    description: cache key
    default: cache-vpm-build-listing-json-${{ github.action_ref }}
    required: false
  disable-cache:
    description: disable cache
    default: false
    required: false

runs:
  using: node20
  main: dist/index.js
